
# Who is SWASI?

The [<span style = "color: #DF63A4">Student Wellbeing and Success Initiative</span>](https://uoregon-my.sharepoint.com/:u:/g/personal/clark13_uoregon_edu/EY4zzGdo3o9ImgpS89tM2wAB4CrNAqmPyAxDAZQ-mNuzJw){target="_blank"} is:

* an ongoing, multicohort, longitudinal research program designed to holistically understand institutional inputs to undergraduate students’ wellbeing and success across the college experience
* an educational program designed to equitably improve wellbeing and success outcomes, particularly among historically marginalized populations (e.g., first-generation students, Black students)
* an assessment and evaluation program designed to gauge whether various programmatic activities, including but not limited to the ones internal to the Initiative itself, are meeting their stated goals

Better understanding better informs us, affording opportunities to improve institutional practices that equitably support students’ learning and development and foster their achievement and persistence. Unlike many for-profit companies, which use data to sell people, this is a strategy that uses data to <span style = "color: #11E8FF">empower</span> people.

The Student Wellbeing and Success Initiative is led by Brian Clark, Assistant Director of the [<span style = "color: #DF63A4">Office of Assessment and Research</span>](https://studentlife.uoregon.edu/research){target="_blank"} in the [<span style = "color: #DF63A4">Division of Student Life</span>](https://studentlife.uoregon.edu/){target="_blank"}. It is supported primarily by the Office of the Vice President for Student Life with integral support from units of the Division of Student Life -- the [<span style = "color: #DF63A4">Department of Physical Education and Recreation</span>](https://rec.uoregon.edu/){target="_blank"}, the [<span style = "color: #DF63A4">Erb Memorial Union</span>](https://emu.uoregon.edu/){target="_blank"}, and the [<span style = "color: #DF63A4">Office of the Dean of Students</span>](https://dos.uoregon.edu/){target="_blank"} -- and across campus from many and varied units in [<span style = "color: #DF63A4">Global Engagement</span>](https://international.uoregon.edu/){target="_blank"}, the [<span style = "color: #DF63A4">Office of the Provost</span>](https://provost.uoregon.edu/), [<span style = "color: #DF63A4">Student Services and Enrollment Management</span>](https://ssem.uoregon.edu/){target="_blank"}, [<span style = "color: #DF63A4">UO Libraries</span>](https://library.uoregon.edu/){target="_blank"}, and [<span style = "color: #DF63A4">Undergraduate Education and Student Success</span>](https://uess.uoregon.edu/){target="_blank"}.

